In [0]:
import numpy as np

In [0]:
a=np.random.randint(1,9,(3,3))
b=np.random.randint(1,9,(3,3))
cross_pdt=np.cross(a,b)
dot_pdt=np.dot(a,b)
add_pdt=np.add(a,b)
print(a)
print(b)
print(cross_pdt)
print(dot_pdt)
print(add_pdt)

[[8 8 8]
 [5 3 4]
 [7 6 5]]
[[1 7 1]
 [7 3 8]
 [7 1 7]]
[[-48   0  48]
 [ 12 -12  -6]
 [ 37 -14 -35]]
[[120  88 128]
 [ 54  48  57]
 [ 84  72  90]]
[[ 9 15  9]
 [12  6 12]
 [14  7 12]]


In [0]:
import pandas as pd
file1=pd.read_csv("iris.csv")

In [0]:
file1.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [0]:
file1.isnull().any()

sepal_length    False
sepal_width     False
petal_length    False
petal_width     False
species         False
dtype: bool

In [0]:
diab=pd.read_csv("pima-indians-diabetes.csv",header=None)

In [22]:
diab.head()

0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

In [24]:
diab.isnull().any()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
dtype: bool

In [0]:
dt=pd.read_csv("ex.csv")

In [26]:
dt.isnull().any()

age        True
weight     True
id        False
dtype: bool

In [27]:
dt.fillna(0)

age  weight    id
0  56.0   156.0  2003
1   8.0     0.0  2335
2  12.0   100.0  8785
3   0.0   120.0  7878
4  25.0   160.0  2535
5  10.0   120.0  7896

In [28]:
dt.dropna()

age  weight    id
0  56.0   156.0  2003
2  12.0   100.0  8785
4  25.0   160.0  2535
5  10.0   120.0  7896

In [30]:
dt.fillna(dt.mean(axis=0))

age  weight    id
0  56.0   156.0  2003
1   8.0   131.2  2335
2  12.0   100.0  8785
3  22.2   120.0  7878
4  25.0   160.0  2535
5  10.0   120.0  7896

In [38]:
dt.fillna(np.mean(dt["weight"]))

age  weight    id
0   56.0   156.0  2003
1    8.0   131.2  2335
2   12.0   100.0  8785
3  131.2   120.0  7878
4   25.0   160.0  2535
5   10.0   120.0  7896

In [35]:
dt.iloc[2:4,:2]

age  weight
2  12.0   100.0
3   NaN   120.0

In [0]:
a=dt.loc[2:4,["age","id"]]
b=dt.loc[1:4,["age","id"]]

In [0]:
dt_cat=pd.concat([a,b])

In [55]:
dt_cat

age    id
2  12.0  8785
3   NaN  7878
4  25.0  2535
1   8.0  2335
2  12.0  8785
3   NaN  7878
4  25.0  2535

In [0]:
dt_cat1=pd.concat([a,b],axis=1)

In [62]:
dt_cat1

age      id   age    id
1   NaN     NaN   8.0  2335
2  12.0  8785.0  12.0  8785
3   NaN  7878.0   NaN  7878
4  25.0  2535.0  25.0  2535

In [0]:
dt_cat2=pd.concat([a,b],axis=1,ignore_index=True)

In [60]:
dt_cat2

0       1     2     3
1   NaN     NaN   8.0  2335
2  12.0  8785.0  12.0  8785
3   NaN  7878.0   NaN  7878
4  25.0  2535.0  25.0  2535

In [63]:
a

age    id
2  12.0  8785
3   NaN  7878
4  25.0  2535

In [64]:
b

age    id
1   8.0  2335
2  12.0  8785
3   NaN  7878
4  25.0  2535